apiVersion: noobaa.io/v1alpha1
kind: BucketClass
metadata:
  labels:
    app: noobaa
  name: aws-bc
spec:
  placementPolicy:
    tiers:
      - backingStores:
          - aws-bs
        placement: Spread