apiVersion: noobaa.io/v1alpha1
kind: BucketClass
metadata:
  name: mirror-bucket-class
  namespace: noobaa
spec:
  placementPolicy:
    tiers:
      - backingStores:
#          - remote-noobaa-dc1
          - remote-noobaa-dc2    # Mirrored copy to the DR site
        placement: Mirror