apiVersion: v1
data:
  AWS_ACCESS_KEY_ID: R3JkQmxEdjhHY0E2YVlNSXFGdVA=
  AWS_SECRET_ACCESS_KEY: V05iN0k3d1ExRXQrY1R0cncrN0VCZXVXSW9LYTdYNWFOL0Y0WUUwTg==
  email: YWRtaW5Abm9vYmFhLmlv
  password: V3RtQkh4SUlQZEppcFRwVFMvMkxSZz09
  system: bm9vYmFh
kind: Secret
metadata:
  creationTimestamp: "2025-06-24T05:40:47Z"
  labels:
    app: noobaa
  name: noobaa-admin
  namespace: noobaa
  ownerReferences:
  - apiVersion: noobaa.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: NooBaa
    name: noobaa
    uid: 714731a3-5f5c-46ca-be9b-1696709d5240
  resourceVersion: "908"
  uid: 8322bbe0-7611-4483-840e-69b4271fc035
type: Opaque
