apiVersion: v1
data:
  auth_token: ZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SmhZMk52ZFc1MFgybGtJam9pTmpnMFptUmpNMk5tTUdObU9ESXdNREkyTkRJeU9XUTRJaXdpYzNsemRHVnRYMmxrSWpvaU5qZzBabVJqTTJObU1HTm1PREl3TURJMk5ESXlPV001SWl3aWNtOXNaU0k2SW05d1pYSmhkRzl5SWl3aVlYVjBhRzl5YVhwbFpGOWllU0k2SW01dmIySmhZU0lzSW1saGRDSTZNVGMxTURBMk5ERTRPSDAueC12SmlTV3k4VWlWV0poWTF3V3kxUXZUVllSb09pNlM5bXZqbThPWXg0SQ==
kind: Secret
metadata:
  creationTimestamp: "2025-06-16T08:56:29Z"
  labels:
    app: noobaa
  name: noobaa-operator
  namespace: noobaa
  ownerReferences:
  - apiVersion: noobaa.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: NooBaa
    name: noobaa
    uid: 6d336cb9-2f47-4a04-b93c-01a5da58ae23
  resourceVersion: "9711"
  uid: 45e297f6-1b61-46ef-9969-8ad9d89c95f4
type: Opaque
