apiVersion: v1
data:
  auth_token: ZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SmhZMk52ZFc1MFgybGtJam9pTmpoaFptVmlZVGczTUdVM04yTXdNREk1TjJZNVpUVm1JaXdpYzNsemRHVnRYMmxrSWpvaU5qaGhabVZpWVRnM01HVTNOMk13TURJNU4yWTVaVFl3SWl3aWNtOXNaU0k2SW1Ga2JXbHVJaXdpWVhWMGFHOXlhWHBsWkY5aWVTSTZJbTV2YjJKaFlTSXNJbWxoZENJNk1UYzFOak0xT1RVNU0zMC5OR3VoWU4xWnczelFaaE4tamZNMS1taFd4Yld5SExOV09YM0xpSE1wVUJn
kind: Secret
metadata:
  creationTimestamp: "2025-08-28T05:39:53Z"
  labels:
    app: noobaa
  name: noobaa-endpoints
  namespace: noobaa
type: Opaque
