apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-test
spec:
  containers:
    - name: ubuntu
      image: ubuntu:latest
      command: [ "/bin/sh", "-c" ]
      args:
        - |
          apt update && apt upgrade -y  
          apt install curl unzip iputils-ping -y
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          ./aws/install
          touch env.txt
          apt install screen
          apt install fish -y
          sleep infinity
  restartPolicy: Always
