apiVersion: v1
data:
  auth_token: ZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SmhZMk52ZFc1MFgybGtJam9pTmpnMVlUWXlZVEEwWXpSbU5EWXdNREprWkdJMVpXUmhJaXdpYzNsemRHVnRYMmxrSWpvaU5qZzFZVFl5WVRBMFl6Um1ORFl3TURKa1pHSTFaV1JpSWl3aWNtOXNaU0k2SW1Ga2JXbHVJaXdpWVhWMGFHOXlhWHBsWkY5aWVTSTZJbTV2YjJKaFlTSXNJbWxoZENJNk1UYzFNRGMxTXprMU0zMC54M1B6azFVd0Q0Q2RvZ1lrRGlJZkdnRXk0M0Ntb2xZUzJzS2hTamE0NEE4
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"auth_token":"ZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SmhZMk52ZFc1MFgybGtJam9pTmpnMVlUWXlZVEEwWXpSbU5EWXdNREprWkdJMVpXUmhJaXdpYzNsemRHVnRYMmxrSWpvaU5qZzFZVFl5WVRBMFl6Um1ORFl3TURKa1pHSTFaV1JpSWl3aWNtOXNaU0k2SW1Ga2JXbHVJaXdpWVhWMGFHOXlhWHBsWkY5aWVTSTZJbTV2YjJKaFlTSXNJbWxoZENJNk1UYzFNRGMxTXprMU0zMC54M1B6azFVd0Q0Q2RvZ1lrRGlJZkdnRXk0M0Ntb2xZUzJzS2hTamE0NEE4"},"kind":"Secret","metadata":{"annotations":{},"creationTimestamp":"2025-06-24T08:32:33Z","labels":{"app":"noobaa"},"name":"noobaa-endpoints","namespace":"noobaa","ownerReferences":[{"apiVersion":"noobaa.io/v1alpha1","blockOwnerDeletion":true,"controller":true,"kind":"NooBaa","name":"noobaa","uid":"12c7fbcf-4cd4-48a5-9429-d0fa48de73fd"}],"resourceVersion":"769","uid":"96962e2d-37a0-4580-8c64-61cb0921cb3f"},"type":"Opaque"}
  creationTimestamp: "2025-06-24T08:35:28Z"
  labels:
    app: noobaa
  name: noobaa-endpoints
  namespace: noobaa
  ownerReferences:
  - apiVersion: noobaa.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: NooBaa
    name: noobaa
    uid: 12c7fbcf-4cd4-48a5-9429-d0fa48de73fd
  resourceVersion: "1111"
  uid: 86bf902a-6895-43ad-8965-2cd9718bafb5
type: Opaque
