apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: local-pv-obc-dc1
spec:
  generateBucketName: anisur-dc1
  storageClassName: noobaa.noobaa.io
  additionalConfig:
    bucketclass: local-pv-bucket-class-dc1